services:
  frontend:
    build: ./frontend
    image: yeswanth/frontend:1.0.0
    container_name: frontend
    ports: 
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
  catalogue:
    build: ./catalogue
    image: yeswanth/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build: ./user
    image: yeswanth/user:1.0.0
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart: 
    build: ./cart
    image: yeswanth/cart:1.0.0
    container_name: cart
    depends_on:
    - catalogue
    - redis
  shipping:
    build: ./shipping
    image: yeswanth/shipping:1.0.0
    container_name: shipping
    depends_on:
    - cart
    - mysql
  payment:
    build: ./payment
    image: yeswanth/payment:1.0.0
    container_name: payment
    depends_on:
    - cart
    - user
    - rabbitmq
  mongodb:
    build: ./mongodb
    image: yeswanth/mongodb:1.0.0
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  mysql:
    build: ./mysql
    image: yeswanth/mysql:1.0.0
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "RoboShop@1"
  rabbitmq: 
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
    environment: 
      RABBITMQ_DEFAULT_USER: "roboshop"
      RABBITMQ_DEFAULT_PASS: "roboshop123"

networks:
  default:
    name: roboshopproject
    driver: bridge
    external: false

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq: